name: build

on:
  push:
    branches: [ main ]
    paths:
      - actions/build/**.js
      - actions/build/**.yml
      - actions/build/**.sh
  pull_request:
    branches: [ main ]
    paths:
      - actions/build/**.js
      - actions/build/**.yml
      - actions/build/**.sh

jobs:
  build:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
            }
          - {
              os: ubuntu-20.04,
            }
          - {
              os: ubuntu-latest,
            }
          - {
              os: macos-latest,
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: |
          cd actions/build
          npm install
      - name: Run Tests
        run: |
          cd actions/build
          npm test
      - name: Run Build Action
        uses: ./actions/build
        with:
          path: ./actions/build/test/valid/
